### ISSUE TITLE
[Suggestion] Compatibility for Croptopia

### ISSUE THREAD

**Issue by Zygus42** [dannydjdk/Nutritional-Balance#12]
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric

Despite the link name, it's for Forge also.  It's a fairly new mod and looks good, adding lots of crops, farming and foods.

**Comment by dannydjdk** [comment]
It looks like Croptopia is using standard forge nutrient tags already (at least in 1.18.1), so most of the foods already have nutrients. I'll work on adding the few missing ones.
