### ISSUE TITLE
[Suggestion] Compatibility for SushiGo Crafting

### ISSUE THREAD

**Issue by nivthefox** [dannydjdk/Nutritional-Balance#13]
Please add support for https://www.curseforge.com/minecraft/mc-mods/sushigocrafting!  When I try to add it myself via datapack, I get such insane values as +189.0NU on a single item. :D  Not quite working as intended.

**Comment by dannydjdk** [comment]
Hmm... so you were able to get it to assign nutrients, but the values were high? If so, it sounds like the saturation values for the sushi are probably insanely high. One potential solution is to put a cap on the total NUs a single item can have.

**Comment by dannydjdk** [comment]
@nivthefox Would you be willing to share your data pack files with nutrition item tags? That could save me a some time.

Also, I'll be working on the NU cap soon.

**Comment by nivthefox** [comment]
The relevant portions are here: https://github.com/SoSly/minecraft/tree/1.18.1-2.0.0/overrides/config/openloader/data/Magnivicent%20Modpack/data/forge/tags/items/nutrients

**Comment by dannydjdk** [comment]
1.18-3.0.2 now supports Sushi Go Crafting and has a configurable cap on the amount of nutrients each item can provide. By default, it's set at 20NU which is also the span of the target area. It can be changed in the server config.
