### ISSUE TITLE
[bug] Farmer's delight compat

### ISSUE THREAD

**Issue by LeoBeliik** [dannydjdk/Nutritional-Balance#14]
~~https://www.curseforge.com/minecraft/mc-mods/farmers-delight~~

~~Some foods lack the nutritional value like shepherds_pie, honey_glazed_ham and stuffed_pumpkin due to, what I'll assume, their uncommon crafting mechanic.~~

looking at the mod's tags I see there's already said compat but it doesn't seem to work in my instance, so I'll report this as a bug instead of suggestion.
Tested with FarmersDelight-1.18.1-1.0.3, nutritionalbalance-1.18-3.0.1 and forge 39.0.63

![image](https://user-images.githubusercontent.com/11804768/153710915-269de611-2dbd-4b92-926a-dab02b5abd75.png)

**Comment by dannydjdk** [comment]
Thanks for reporting this! I added Farmer's Delight support when this mod was first released back in 1.16.5. Something must have changed since then.

**Comment by dannydjdk** [comment]
Fix has been released in the 1.18-3.0.2 version. It turns out Minecraft changed how item tags work which is why this wasn't working.
