### ISSUE TITLE
[suggestion] allow to close the mod's gui with the inventory key

### ISSUE THREAD

**Issue by LeoBeliik** [dannydjdk/Nutritional-Balance#15]
It would be more convenient to use the inventory key (or the mod's assigned key) to close the gui instead of having to reach for escape key :)

**Comment by dannydjdk** [comment]
This feature has been released in the 1.18-3.0.2 version.

I may back port this to 1.17 and 1.16, so I'll keep this open for now.

**Comment by dannydjdk** [comment]
Back ported. Waiting on Curseforge.
