### ISSUE TITLE
Incompatible with Water Source

### ISSUE THREAD

**Issue by SeanChengN** [dannydjdk/Nutritional-Balance#16]
1.18.1-Forge_39.0.88
nutritionalbalance-1.18-3.0.2
watersource-1.3.65-release-1.18.1
https://github.com/lemon-slice-studio/WaterSource

log:
[crash-2022-03-11_10.07.13-server.txt](https://github.com/dannydjdk/Nutritional-Balance/files/8228447/crash-2022-03-11_10.07.13-server.txt)

Installing both mods at the same time will result in loss of nutrient content data, and if you eat food without nutrient data, it will cause a crash.

Without watersource:
![o43bjxut8M](https://user-images.githubusercontent.com/20624068/157789984-9771c91e-699d-4110-8b33-37cb6c28fd45.png)
![BvUMXyELWq](https://user-images.githubusercontent.com/20624068/157789997-4cb466a7-ab1d-4ea3-9ad1-12c461df825b.png)

With watersource:
![ARbTkhONsK](https://user-images.githubusercontent.com/20624068/157790058-e37795c8-f37a-492c-aebc-ceaa78b1dafd.png)
![6PaXtwvbuq](https://user-images.githubusercontent.com/20624068/157790070-dcbb621d-27fb-440d-9e46-41b1ba6c0c40.png)

**Comment by dannydjdk** [comment]
Hmm... not sure why WaterSource is registering null recipes, but I can check for that. I should have a fix for this soon.

**Comment by dannydjdk** [comment]
Fixed in 1.18.1-3.0.3
