### ISSUE TITLE
ServerConfig File Resetting

### ISSUE THREAD

**Issue by Blueberrypie255** [dannydjdk/Nutritional-Balance#17]
Hi! I have added this mod nito a server, and I have found a problem. When I reset the server with a changed serverconfig file, the changed file gets reset back to the old one. Can you fix this?

**Comment by dannydjdk** [comment]
Configs are managed by Forge. Mods only hooks into them, so this is not likely related to the mod.
I can try to help you track down the problem.  I'll need more information, though.
Which versions of the mod and forge are you using?
Where, exactly, is the config file that you are modifying located and what is  the filename?

**Comment by Blueberrypie255** [comment]
I am using the file inside the world settings. When i reset my server (using shockbyte for hosting; forge version 39.0.76; mod version "nutritionalbalance-1.18-3.0.2.jar"). Also, I changed the engorge in the config, but the effect still comes at 170 NU (the default). Why is this happening? I have linked a copy of the nutritionalbalance-server.toml (saved as a zip file). The only issue I have found is the engorge and this config file resetting when I restart my server.
[nutritionalbalance-server.zip](https://github.com/dannydjdk/Nutritional-Balance/files/8236812/nutritionalbalance-server.zip)

**Comment by dannydjdk** [comment]
It looks like you changed a comment on line 19 which should read:
`		#Engorgement value, above which bad affects can occur.(default:170.0)`
Forge is really finicky about comment values. That might be the problem, though maybe you changed that to try to fix this problem(?).

Just to be clear, all the setting except engorgement value are working correctly (before it gets reset), right?

You might want to try also adding your modified server config file into the "defaultconfigs" folder under the server instance root direct, just in case some mod is trying to reset configs from there.

**Comment by Blueberrypie255** [comment]
So I can move the worldconfig file into the Config file? Will this break anything?

**Comment by dannydjdk** [comment]
Specifically, a folder called "defaultconfigs". This is different than the "config" folder. Normally, it's where you would put server configs that you want all new worlds to get.

**Comment by Blueberrypie255** [comment]
Do you have Discord? I would like to screenshare my screen. I do not see a "defaultconfigs" folder.

**Comment by dannydjdk** [comment]
It doesn't exist by default. You need to create it.
Also, you can try this file. I reset everything except the values you changed. This can help rule out any issues with the config file itself.
[nutritionalbalance-server.toml.zip](https://github.com/dannydjdk/Nutritional-Balance/files/8236940/nutritionalbalance-server.toml.zip)

**Comment by Blueberrypie255** [comment]
I should create the file in my default directory? Sending a picture.
![Uploading pic.PNG…]()

**Comment by Blueberrypie255** [comment]
I should make a new folder here? The world is BlueCraft MineColonies.

**Comment by Blueberrypie255** [comment]
![pic](https://user-images.githubusercontent.com/96138089/158001909-a2a36320-dbbe-4b1e-967e-32a74f4f5fb4.PNG)

**Comment by Blueberrypie255** [comment]
There is the picture.

**Comment by dannydjdk** [comment]
Yes. That's where the defaultconfigs folder should be. Make sure you fix that comment though or use the file that I sent.

**Comment by Blueberrypie255** [comment]
Let me try... I will tell you in about 5 minutes after the server restarts.

**Comment by Blueberrypie255** [comment]
Should I delete the config in my world folder?

**Comment by dannydjdk** [comment]
K. Feel free to join our Discord server: https://discord.gg/txjRhjR
Might be a better forum for this.

**Comment by dannydjdk** [comment]
Not necessarily. I would replace it with the one I sent though.
