### ISSUE TITLE
Spice of Life: Potato Edition compability

### ISSUE THREAD

**Issue by DrSigma4164** [dannydjdk/Nutritional-Balance#19]
In the [Spice of Life: Potato Edition](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-potato-edition) mod, there are things like lunch boxes, you put food in them and he chooses one of them and eats it. However, if you eat food in this way, proteins, carbohydrates, fruits, vegetables, etc. are not recognized by your mod, that is, I do not get points for the food I eat, using the lunchbox.

**Comment by dannydjdk** [comment]
Unfortunately, this is not possible. See duplicate issue #5 for details.
