### ISSUE TITLE
1.16.5 config issue

### ISSUE THREAD

**Issue by Swifty744** [dannydjdk/Nutritional-Balance#22]
If you change the config you have to restart the world in order for it to apply the changes. You can't change the diet config while the world is on. Shame.

**Comment by dannydjdk** [comment]
Have you typed "/reload"?

**Comment by Swifty744** [comment]
I reloaded my game but I'll give this a try instead.

**Comment by dannydjdk** [comment]
As a general rule for any mod and vanilla, you need to type "/reload" for new server configs and data packs to take affect.

Also check out the Nutritional Balance wiki for more info: https://github.com/dannydjdk/Nutritional-Balance/wiki/Customization-and-Integration
