### ISSUE TITLE
config edit issues 1.16.5

### ISSUE THREAD

**Issue by Marshmalllow09** [dannydjdk/Nutritional-Balance#29]
Using Forge, Roguelike adventures and dungeons, 1.16.5, hosted through apex minecraft hosting.
In defaultconfigs I am trying to add protein to the effect_good_nutrients, however it is not being adjusted after /reload and server restart. I have edited both defaultconfig and world config. Nothing.

**Comment by dannydjdk** [comment]
Thanks for the report!
Defaultconfigs only affects new worlds, so you do need to edit the configs within the world file to affect the existing world.
The line should look exactly like this:
		effect_good_nutrients = ["vegetables", "proteins"]

Also, if a player is already engorged, you do need to run the command "/nb reset_player_effect"

If it's still not working, please paste your config file.
If this fixes your issue, please let me know that too.

Thanks!
