### ISSUE TITLE
Hovering over foods with a lot of aspects causing FPS lag in JEI.

### ISSUE THREAD

**Issue by JJSax** [dannydjdk/Nutritional-Balance#3]
This was more noticeable with more mods, but I reduced my mods to JEI, Pam's Harvestcraft, and this one to narrow it down. 

With just these 3 mods, if I hover over something like Cinnamon toast I get down to about 30 FPS.  Hovering over something like a grindstone or any non-food item I get 65-75 fps.  With my full fairly modest mod list I was getting down below 1 fps.  Taking out this mod I get 70-80 fps even when hovering over cinnamon toast.

**Comment by dannydjdk** [comment]
Thanks for reporting this! This should be fixed in 1.16.5-0.7.3.
