### ISSUE TITLE
'Cannot read field "name" because "nutrient" is null' when drinking [Let's Do] Vinery wines without nutrition values

### ISSUE THREAD

**Issue by zckss** [dannydjdk/Nutritional-Balance#36]
Some wines don't include any known ingredients with nutrients.  Drinking those wines causes a crash.  Expected result for a drink with no nutrients defined would be to simply not affect nutrients.

Minecraft version: 1.19.2
Nutritional-Balance version: nutritionalbalance-1.19.2-4.2.3
Forge version: 43.3.0
[Let's Do] Winery version: letsdo-vinery-forge-1.3.12b

[crash-2023-11-10_22.48.58-server.txt](https://github.com/dannydjdk/Nutritional-Balance/files/13325073/crash-2023-11-10_22.48.58-server.txt)

**Comment by dannydjdk** [comment]
Thanks for the report! Fix has been posted to curseforge, is currently under review, and will be available shortly.
