### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by BlazeGaminginit** [dannydjdk/Nutritional-Balance#7]
Would you ever make Nutritional-Balance mod available for 1.12.2 version of Minecraft

**Comment by dannydjdk** [comment]
Sorry, there are no plans to back port this mod. There is a very similar mod for 1.12.2 called Nutrition. It's not on Curseforge, but it is allowed in Curseforge packs. You can download it here: https://github.com/WesCook/Nutrition/releases

**Comment by BlazeGaminginit** [comment]
> Sorry, there are no plans to back port this mod. There is a very similar mod for 1.12.2 called Nutrition. It's not on Curseforge, but it is allowed in Curseforge packs. You can download it here: https://github.com/WesCook/Nutrition/releases

thx
